//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        public Producer()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ProducerID { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
