//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Receipt_Product = new HashSet<Receipt_Product>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int ProductID { get; set; }
        public int ProducerID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public int BarCode { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual ICollection<Receipt_Product> Receipt_Product { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
