//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Product
    {
        public int ReceiptProductID { get; set; }
        public int ProductID { get; set; }
        public int ReceiptID { get; set; }
        public int Quantity { get; set; }
        public double TotalPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
