//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public Receipt()
        {
            this.Receipt_Product = new HashSet<Receipt_Product>();
        }
    
        public int ReceiptID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Receipt_Product> Receipt_Product { get; set; }
    }
}
